name: bekushal
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
#  flutter_icons: ^1.1.0
  shared_preferences: ^2.1.2
  flutter_switch: ^0.3.2
  dots_indicator: ^3.0.0
  provider: ^6.0.5
  image_picker: ^1.0.0
  dropdown_button2: ^2.1.4
  line_icons: ^2.0.3
  wave_linear_progress_indicator: ^0.1.0
  im_stepper: ^1.0.1+1
  easy_stepper: ^0.7.2
  percent_indicator: ^4.2.3
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/data/
    - assets/gif/
    - assets/questions/
    - assets/questions/pandas_and_numpy/
    - assets/questions/supervised_learning_basics/
    - assets/questions/artificial_neural_networks/
    - assets/questions/unsupervised_learning_basics/
#    - assets/questions/computational_linguistics/
#    - assets/questions/computer_vision/
    - assets/questions/logic_programming/
#    - assets/questions/deep_learning/
#    - assets/questions/speech_processing/
#    - assets/questions/natural_language_processing/
#    - assets/questions/conversational_ai/
#    - assets/questions/generative_ai/